# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: GCPLoadBal"
$Body = @'
{
  "Name": "GCP Load Balancer",
  "ShortName": "GCPLoadBal",
  "Capability": "GCPLoadBal",
  "ServerRequired": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Optional",
  "PowerShell": false,
  "PrivateKeyAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "Properties": [
    {
      "Name": "jsonKey",
      "DisplayName": "Service Account Key",
      "Required": true,
      "IsPAMEligible": false,
      "DependsOn": "",
      "Type": "Secret",
      "DefaultValue": "",
      "Description": "If authenticating by passing credentials from Keyfactor Command, this is the JSON-based service account key created from within Google Cloud.  If authenticating via Application Default Credentials (ADC), select No Value"
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

